const numeroA = 1;
const numeroC = 3;

try {
    console.log(numeroA);
    console.log(numeroB);
    console.log(numeroC);
} catch (error) {
    console.log(error);
}
